### ISSUE TITLE
menu on left sometimes gets stuck

### ISSUE THREAD

**Issue by kylemcdonald** [processing/p5.js-website-OLD#127]
it's hard to replicate this behavior, but sometimes when i'm switching between tabs the menu on the left gets stuck somewhere offscreen.

if you switch between absolute and fixed positioning it would probably solve this. here's a demo

http://jsfiddle.net/M3KLB/1/

but you'd lose the excellent bouncy behavior you have right now :/

if i can reliably replicate the bug i'll update this issue.

**Comment by digitalfrost** [comment]
Stale ticket. 
Website has a new version.
Ticket can be closed.
