### ISSUE TITLE
mouse cursor  not reacting...

### ISSUE THREAD

**Issue by kusha-b-k** [processing/p5.js-website-OLD#235]
in p5.js website, when i open the examples page like (https://p5js.org/examples/examples/Simulate_Particle_System.php) in chrome browser the mouse cursor of my system is not reacting for some time. ( my internet speed is 50 mbps )

**Comment by limzykenneth** [comment]
I wasn't able to replicate but I think it might have more to do with the system...Can I know what version of Chrome are you using and also the OS (incl version) you are using? Cheers.

**Comment by kusha-b-k** [comment]
mac os 10.10, chrome v46+

thanks..

**Comment by digitalfrost** [comment]
Updated URL of Particle System Example: http://p5js.org/examples/simulate-particle-system.html

Works fine for me with Chrome Version 53.0.2785.143 .
Not able to replicate problem.

Can be closed ?
