### ISSUE TITLE
should be able to get to p5.sound and p5.dom library overview pages from main ref page (search?)

### ISSUE THREAD

**Issue by lmccart** [processing/p5.js-website-OLD#41]

**Comment by digitalfrost** [comment]
Are you satisfied with:
_

> You may want to check out [p5.dom](https://p5js.org/reference/#/libraries/p5.dom) or [p5.sound](https://p5js.org/reference/#/libraries/p5.sound)

._ 
on the new P5.js website: https://p5js.org/reference/  ?
