### ISSUE TITLE
Local server can't find CSS files

### ISSUE THREAD

**Issue by zacharystenger** [processing/p5.js-website-OLD#98]
While setting up my local Apache server I noticed I wasn't getting any of the CSS. This was because in header.php the CSS is getting included like this:  
```HTML+PHP
<link rel="stylesheet" href="<?php echo getRoot(); ?>css/main.css">
```
and getRoot() returns p5js.org but the directory is named p5.js-website, so it looks in a place that doesn't exist.  Renaming my directory to p5js.org made everything work. This was all on a machine running Ubuntu.  
I thought it would be good to include a note about this issue in the set up description.

**Comment by lmccart** [comment]
yes!

**Comment by digitalfrost** [comment]
Can be closed, since new version of website no longer using php.
